### ISSUE TITLE
Syslog

### ISSUE THREAD

**Issue by drewsymo** [WPWhiteSecurity/WP-Security-Audit-Log#24]
Is it possible to log all E_CRITICAL notifications to php syslog()?

**Comment by robert81** [comment]
HI Drewsymo,

Thank you for getting in touch. Syslog is definitely something we want to integrate to but never really looked into it so far. Though rest assured that it is something we will be working on in the future. Since we do not have any concrete plans yet we do not have an ETA though you can subscribe to our plugins newsletter to keep yourself updated with the progress of our plugin: http://eepurl.com/Jn9sP
