### ISSUE TITLE
Tagging versions in git

### ISSUE THREAD

**Issue by Duologic** [WPWhiteSecurity/WP-Security-Audit-Log#376]
Hi

We currently use a setup for creating a release of our Wordpress setup where we make use of Git Submodules. To pin to a fixed version, we checkout a certain version, usually an a tag in git.

I noticed that you guys didn't 'tag' the version in git, is there a reason for this? 

Thanks

**Comment by WPWhiteSecurity** [comment]
Hello,

First of all thank you for using our plugin.

Regarding the tags, it just didn't occur to us to tag the plugin versions on Github as well since we already do that on the WordPress repository; https://en-gb.wordpress.org/plugins/wp-security-audit-log/developers/

Though knowing there is a need for is moving forward we will start tagging them. Thank you for pointing this out.

**Comment by Duologic** [comment]
Alright, you guys are awesome! 👍

**Comment by WPWhiteSecurity** [comment]
@Duologic you're welcome. Would appreciate if you can spare a minute to rate our plugin: https://wordpress.org/support/plugin/wp-security-audit-log/reviews/

Thank you and have a good weekend.
