### ISSUE TITLE
Wonolog support?

### ISSUE THREAD

**Issue by strarsis** [WPWhiteSecurity/WP-Security-Audit-Log#499]
Is support for [Wonolog](https://github.com/inpsyde/Wonolog) planned?
This makes it much easier for plugins to log in a unified way.

**Comment by WPWhiteSecurity** [comment]
Thank you for your comment @strarsis 

Yes, we have it in our to do list. However, at this stage I cannot give you an ETA when the feature will be available since Wonolog is not that widely used. When it becomes more popular and there is more demand for it we will surely give this task priority.

I hope the above answers your question. Should you have any further questions please do not hesitate to ask.

**Comment by strarsis** [comment]
@WPWhiteSecurity: Where can I find the documentation or an example for a plugin logging something to `WP-Security-Audit-Log`?

**Comment by WPWhiteSecurity** [comment]
We have an _API_ which you can use. It is documented here: https://www.wpsecurityauditlog.com/support-documentation/create-custom-alerts-wordpress-audit-trail/

This is a plugin someone built around this API: https://wordpress.org/plugins/wp-security-audit-log-for-paid-memberships-pro/

Hope the above helps. Should you require any further information please do not hesitate to get in touch. 

Have a great day.
